### PR TITLE
Strict object validation

### PR DESCRIPTION
**Pull request by fabioanderegg**
I propose the addition of strict object validation:
Validate objects to only allow fields that are referenced in the props dictionary of an object.
```js
const schema = {
    obj: {
        type: "object",
        props: {
            a: "string"
        },
        strict: true
    }
};

console.log(v.validate({ obj: { a: "string" } }, schema));
// Returns: true

console.log(v.validate({ obj: { a: "string", b: "string" } }, schema));
/* Returns an array with errors:
[ { type: 'objectStrict',
    expected: 'b',
    actual: undefined,
    field: 'obj',
    message: 'The object \'obj\' contains invalid keys: b!' } ]
*/
```

Perhaps someone has a better name than "strict object validation" for this.

The performance impact with `npm run bench` is not measurable, but adding a separate "strictObject" validator is certainly possible if this is a problem.

### CODE REVIEW

**Comment by icebob** [comment]
Nice PR, thanks. Would be good to add a strict property to the root object too (e.g. $$strict: true). What do you think?

**Comment by mbaertschi** [comment]
@icebob I added the `$$strict: true` option on schema root level and enhanced the README.md accordingly

**Comment by icebob** [comment]
Could you resolve merge conflicts?

**Comment by icebob** [comment]
Released https://github.com/icebob/fastest-validator/releases/tag/v0.6.14

**Pull request merged**
