### PR TITLE
feat(uuid): support uuid v6

### PR DESCRIPTION
**Pull request by intech**
Added support for uuid v6, which is a modified version from uuid v1 with lexicographic order for sorting.
Ref: https://www.npmjs.com/package/uuid-v6

### CODE REVIEW

**Comment by intech** [comment]
@erfanium done

**Comment by icebob** [comment]
@intech something happened after I merged. CI test failed: https://github.com/icebob/fastest-validator/runs/941547306?check_suite_focus=true#step:5:37

**Comment by intech** [comment]
@intech one moment

**Comment by intech** [comment]
@icebob done. Sorry.

**Pull request merged**
