### PR TITLE
Reach TypeScript Definitions

### PR DESCRIPTION
**Pull request by akazakou**
Added reach Type Definition file
* Implemented validation of properties for each available built-in validation rules
* Implemented supporting of a custom validation rule definition
* Added support of messages in types description

### CODE REVIEW

**Comment by akazakou** [comment]
@icebob could you please check this one?

**Comment by icebob** [comment]
Thanks @akazakou, I've checked, but I'm not a Typescript guy, so I don't know it will be good for everyone.

**Comment by akazakou** [comment]
I believe that all should be fine. I tried it in my project and it builds successfully.

**Comment by icebob** [comment]
I've released in v0.6.17

**Comment by akazakou** [comment]
Thank you. To me, all looks fine with the latest version.

**Pull request merged**
