### PR TITLE
[feature] added rule for currency validation

### PR DESCRIPTION
**Pull request by ishan-srivastava**
Regarding [this](https://github.com/icebob/fastest-validator/issues/110) feature request.

### CODE REVIEW

**Comment by icebob** [comment]
@ishan-srivastava thank you for your job on this PR.
I see this rule can cover the familiar currencies like, $, €, £ but not all.
In my country, the format of currency is: `1 234,56Ft`
As you see, the thousand separator is space, the decimal separator is a comma and the sign at the end and two characters. Fully different, I know :)

image

Since you are using regex for testing, I think it would be hard to cover all types. The easier way can be that if we can set different checker regexp in the rule params. What do you think @ishan-srivastava @erfanium ?

**Comment by ishan-srivastava** [comment]
Sure @icebob , that makes sense.
For what I can see is, that the validation logic can be changed by these params.
1. Currency ~~symbol~~ **string** [ having options to make it optional, and case insensitive.]
2. The currency is in prefix or postfix [default to prefix]
3. String to allow between the Currency and digits in the format of 
     a.) {**character**, minimum occurrences allowed, maximum occurrences allowed (_leave blank for infinity_) }
     b.) false if no String is allowed between the currency and digits.
4. Character for decimal [deafults to a '.'].
5. Character for thousand separator [deafults to a ',']

What we can also do is to extend the regex for the end-user to provide (in the schema), and that would override all the inbuilt validations the currency validator does, and would simply check the provided value against the regex provided by the user.

What do you think @icebob @erfanium ?

**Comment by icebob** [comment]
Yeah, and please support negative currencies as well. I didn't see tests for negative values.

**Comment by erfanium** [comment]
> What do you think @ishan-srivastava @erfanium ?

This is a good idea, ‌But I don't think we need to support all currencies, We can first support some important currencies and And wait for user issues/PRs 🙂

**Comment by ishan-srivastava** [comment]
@erfanium sure.
I think that in order to support more currencies, we would need to add more and more logic on top of existing logic, which won't be scalable.
Like you said : Adding a param that takes in a custom currency validator name, eg currency_rial / currency_hungarian_forint, sounds good to me.
The current logic would support all the currencies that have 
a.) ',' as the thousand separator.
b.) '.' as decimal separator.
c.) Currency symbol is a single character, prefixed before the digits

Should I go ahead and add the changes I suggested, or just simply support -ve values and update the PR?

**Comment by icebob** [comment]
As @erfanium said, we don't need to support all currencies. So as you described, just add some property like thousand separator and decimal separator and a custom regexp pattern. So if I want to check Hungarian forint with this rule, I will define a custom regexp and set it to the rule.

**Comment by ishan-srivastava** [comment]
> Just add some property like thousand separator and decimal separator and a custom regexp pattern. 

Sure, I'll add that in this week, day job has turned v hectic :p

**Comment by ishan-srivastava** [comment]
@icebob I have added the following

1. Feature to pass decimal separator
2. Feature to pass thousand separator
3. Feature to support negative currencies
4. Feature to support custom regex.

Please have a look.

**Comment by erfanium** [comment]
@icebob What's the status of this issue?

**Comment by icebob** [comment]
It's waiting for my review. I was busy but I will review it this week.

**Review by icebob — APPROVED** [review]
Good job @ishan-srivastava, thanks!

**Comment by icebob** [comment]
Released in 1.7.0

**Pull request merged**
