### PR TITLE
Add table of contents to the README.md

### PR DESCRIPTION
**Pull request by adam-mccormick**
Hopefully makes it easier to navigate the documentation. I find myself referring to this a lot and wish this was there.

### CODE REVIEW

**Comment by erfanium** [comment]
Screenshot from 2022-06-07 10-16-53
Github has a built-in index

**Comment by adam-mccormick** [comment]
@erfanium Sure but other places, like npm.com, do not.

**Review by AndreMaz — APPROVED** [review]

**Comment by AndreMaz** [comment]
Thank you @adam-mccormick :+1:

**Comment by erfanium** [comment]
https://github.com/icebob/fastest-validator/commit/8860c6e9e7793417f37908a6f6dd9fa4206f58ff

**Comment by icebob** [comment]
Yeah, @erfanium has right, Github has built-in ToC, this is why we removed and generating ToC caused problem in the past. Thank you for your effort, but I close it.

**Pull request closed without merging**
