### PR TITLE
Refactor index.d.ts and ts tests

### LINKED ISSUE #171: Deno + TS => Doesn't work
Because `jspm.io` doesn't support typescript, so types will not be included.
If anyone has an idea, offer it

### PR DESCRIPTION
**Pull request by erfanium**
fixes #171

### CODE REVIEW

**Review by icebob — COMMENTED** [review]
I cannot judge whether it is good or not. Can it cause a breaking issue for TS users?

**Comment by erfanium** [comment]
As tests are working, it should work. Also fixes typescript problem with Deno.

**Comment by icebob** [comment]
Why I get a lot of ts errors when I run `npm test` locally?
image

**Comment by icebob** [comment]
It works after a `npm run build`. Why TS unit tests use the d.ts file from the dist?

**Comment by erfanium** [comment]
Screenshot from 2021-07-14 22-31-53
It works for me, without `npm run build`, with node v16.2.0
If you have installed `ts-node`, or `typescript` globally, remove it

**Pull request merged**
