### PR TITLE
support default and optional in tuples and arrays

### LINKED ISSUE #175: tuple item dosent support default and optioanl
default
```ts
const V = require('fastest-validator');

const v = new V();

const schema = {
  tuple: {
    type: 'tuple',
    empty: false,
    items: [{ type: 'string', default: '1' }],
  },
};

const data = { tuple: [] };
console.log(v.validate(data, schema));
console.log(data);
```

```text
[
  {
    type: 'tupleEmpty',
    message: "The 'tuple' field must not be an empty array.",
    field: 'tuple',
    actual: []
  }
]
{ tuple: [] }
```

optional
```ts
const schema = {
  tuple: {
    type: 'tuple',
    empty: false,
    items: [
      { type: 'string' },
      { type: 'number', optional: true },
    ],
  },
};

const data = { tuple: ['str', undefined] };
console.log(v.validate(data, schema));
console.log(data);
```

```text
[
  {
    type: 'number',
    message: "The 'tuple[1]' field must be a number.",
    field: 'tuple[1]',
    actual: undefined
  }
]
{ tuple: [ 'str', undefined ] }
```

### PR DESCRIPTION
**Pull request by eyalpost**
Resolves #175 
Solution: Set "value" variable to the item being validated. Similar to how properties are validated in object.js

### CODE REVIEW

**Review by erfanium — APPROVED** [review]
Great👍

**Review by icebob — CHANGES_REQUESTED** [review]
LGTM, but please add the these tests to the integration.spec.**js**, as well.

**Comment by eyalpost** [comment]
> LGTM, but please add the these tests to the integration.spec.**js**, as well.

@icebob Done

**Review by icebob — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
